name: floater
description: A framework that floats over flutter as a higher level construct to provide architecture and structure for complex flutter apps.
version: 0.1.5+1
homepage: https://github.com/shreymahendru/floater

environment:
  sdk: ">=3.10.1 <4.0.0"
  flutter: ">=3.38.0 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.17.0
  get_it: ^9.2.0
  flutter_secure_storage: ^10.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
